### ISSUE TITLE
Replace svg style with attributes.

### ISSUE THREAD

**Issue by Oreilles** [pshihn/rough#151]
Is there any reason why you choose to set SVG props with inline styling: `path.style.stroke = 'none'`  instead of attributes, with `path.setAttribute('stroke', 'none')` ?

Using SVG attributes instead of inline styling would make it possible to style svgs with css in the context of a web page, it currently isn't because inline style attributes win over css stylesheets.

https://github.com/pshihn/rough/pull/155

**Comment by pshihn** [comment]
CSS Properties may be the way to go in your case. Set the stroke/fill to `var(--my-color)`
Then on your parent node just set the prop to whatever color you want

```css
svg {
  --my-color: red;
}

svg.nostroke {
   --my-color: none;
}
```

**Comment by Oreilles** [comment]
Sure, but then it's not possible to use css animation. This doesn't work:

```css
svg {
  --fill: black;
  animation: animate_fill 3s infinite;
}
@keyframes animate_fill {
    from { --fill: red }
    to   { --fill: blue }
}
```

Changing to attributes would be a tiny change in the code base, and I highly doubt it would break anyone's markup. Another reason for the switch would be markup readability and ease of manipulation.
